title: "Sergio Rus"
description: "Hi, I'm Sergio. I'm a software engineer really excited about the Web Platform and web performance."
schema_type: "https://schema.org/Article"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "article"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
paginate: 5
paginate_path: "/blog/page:num/"
permalink: "/blog/:title-:year:month:day/"
