title: "Sergio Rus"
description: "Hi, I'm Sergio. I'm a software engineer really excited about the Web Platform and web performance."
canonical_url: "https://www.sergiorus.com"
schema_type: "https://schema.org/Article"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
